name: discord_reddit_bot
channels:
  - conda-forge
dependencies:
  - python=3.9.12  # Keeping your specific Python version
  - pip=24.3.1
  - sqlalchemy=2.0.37  # From your original file
  - python-dotenv=1.0.1
  - discord.py=2.3.2
  # Testing dependencies
  - pytest=8.3.4
  - pytest-asyncio=0.25.2
  # Database dependencies
  - mysql-connector-python=9.0.0
  - pymysql=1.1.1
  # Core dependencies for async operations
  - aiohttp=3.11.11
  - asyncio
  - pip:
    - asyncpraw==7.8.1  # Reddit API wrapper
    - praw==7.8.1       # Reddit API wrapper
    - asyncprawcore==2.4.0
    - urllib3==2.3.0    # Required by requests
    - requests==2.32.3  # Required by healthcheck