name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out repository code

    - name: Build Docker image
      run: docker build . -t seraph_docker_1:v1.0

    - name: Run tests using Docker
      run: docker run --rm seraph_docker_1 pytest 
